### ISSUE TITLE
deploy action should support --service-name param

### ISSUE THREAD

**Issue by nodirnasirov** [fastly/compute-actions#22] opened 2022-08-23 16:21 UTC
It would be big help if there was `--service-name` param support for fastly deploy action. Fastly CLI has --service-name, so It think it should not be a big change

**Comment by kailan** [comment] 2022-08-23 16:25
Hi @nodirnasirov –– I'm wondering what your use case is here. From my past experience, the service name is something that would bet set once rather than upon every deployment. Are you perhaps looking to provision new services for each deployment?

**Comment by nodirnasirov** [comment] 2022-08-23 17:31
so here is the use case:
I have a codebase I want to deploy into multiple existing services
I have setup github workflow that uses matrix of service ids and deploys them (codebase is built leveraging fastly env vars)
I wanted to provide service name instead of service ids, it will make my action output more human readable.
`fastly compute deploy --service-name=foo` does not create new service, but it deploys into existing fastly service.

**Comment by nodirnasirov** [comment] 2022-08-23 21:22
When do you think this can be merged and available?

**Comment by kailan** [comment] 2022-08-31 17:36
Confirmed with reporter that this is no longer a requirement via Slack, so will close the issue.

If anyone is reading this in the future because you need the same thing, feel free to leave a comment and this can be reopened :)

**Closed by kailan** 2022-08-31 17:36 UTC
Labels: enhancement
